name: C# Syntax Check CI

on: [push, pull_request]

jobs:
  warnings:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Dependencies
      run: dotnet restore

    - name: Install Roslyn Analyzers
      run: dotnet add ApiChessClub.csproj package Microsoft.CodeAnalysis.NetAnalyzers

    - name: Build with RA
      run: dotnet build --no-restore -c Release